export const LOGIN_FAILED = "Login attempt failed!";
export const SIGNUP_FAILED = "Signup attempt failed!";
export const LOGOUT_FAILED = "Logout attempt failed!";
export const TOKEN_REFRESH_FAILED =  "Token refresh attempt failed!";
export const INCORRECT_CREDENTIALS = "Incorrect username or password!";
export const INVALID_SESSION = "Invalid Session!";
export const SESSION_ERROR = "Session error!";
export const EMAIL_ALREADY_PRESENT = "Email already taken!";
export const LOGOUT_SUCCESSFULL = "You are logged out!";
export const USER_UPDATE_SUCCESSFULL = "User updated successfully";

export const SOMETHING_WENT_WRONG = "Something went wrong!";
export const USER_EMAIL_NOT_FOUND = "User not found with this email id!";
export const USER_ID_NOT_FOUND = "User not found with this id!";
export const INVALID_EMAIL_OR_TOKEN = "Invalid token or email!";
export const INVALID_ACCESS_TOKEN = "Invalid access token!";
export const INVALID_REFRESH_TOKEN = "Invalid refresh token!";
export const ACCESS_TOKEN_EXPIRED = "Access token expired!";
export const REFRESH_TOKEN_EXPIRED = "Refresh token expired!";